app = "innovisa-ai-api"
primary_region = "ams"

[build]

[env]
  CHROMA_PERSIST_DIRECTORY = "/data/chroma_db"
  ANONYMIZED_TELEMETRY = "False"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/api/v1/health"

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "innovisa_data"
  destination = "/data"
