"""
Database seed script for InnoVisa AI.

Populates sectors, ideas, documents, competitions, and a test user.
Uses Claude API for generating realistic idea/document descriptions when
API keys are available; falls back to hand-written content otherwise.

Run: python seed.py  (from backend/ directory, with venv activated)
"""

from __future__ import annotations

import hashlib
import json
import random
import sys
import os
from datetime import datetime, timezone, timedelta, date
from pathlib import Path

# Ensure the backend package is importable
sys.path.insert(0, str(Path(__file__).resolve().parent))
os.chdir(Path(__file__).resolve().parent)

from dotenv import load_dotenv
load_dotenv()

from app.database import engine, SessionLocal, Base
from app.models import (
    User, Sector, Idea, Document, Competition, SavedIdea,
    SubscriptionTier, TrendDirection, DocType, CompetitionStatus,
)
from app.dependencies import hash_password
from app.config import get_settings

settings = get_settings()

# Attempt to import RAG engine for embeddings (optional – seed still works without API keys)
try:
    from app.rag_engine import RAGEngine
    _rag = RAGEngine()
    HAS_RAG = True
except Exception:
    HAS_RAG = False
    _rag = None
    print("WARNING: RAG engine unavailable (check API keys). Documents will be seeded without embeddings.")

NOW = datetime.now(timezone.utc)


def _hash(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def seed_sectors(db):
    if db.query(Sector).count() > 0:
        print("Sectors already seeded, skipping.")
        return

    data = [
        {"name": "Health", "description": "Digital health, MedTech, NHS innovation, biotech, and personalised medicine. The UK government has committed to making the NHS the world's most advanced health system through technology adoption.", "icon_name": "Heart", "priority_score": 9.0, "funding_available_gbp": 500_000_000, "trend_direction": TrendDirection.up},
        {"name": "IT", "description": "Software, AI/ML, cybersecurity, cloud computing, and deep-tech. The UK's digital sector contributes over £150bn to the economy and is a top priority for Innovate UK funding.", "icon_name": "Cpu", "priority_score": 10.0, "funding_available_gbp": 750_000_000, "trend_direction": TrendDirection.up},
        {"name": "Ecommerce", "description": "Online marketplaces, D2C platforms, retail-tech, logistics automation, and payment innovation. UK ecommerce is the third largest market globally.", "icon_name": "ShoppingCart", "priority_score": 7.0, "funding_available_gbp": 200_000_000, "trend_direction": TrendDirection.stable},
        {"name": "Agriculture", "description": "AgriTech, precision farming, sustainable food systems, vertical farming, and supply chain transparency. Post-Brexit agricultural policy prioritises innovation.", "icon_name": "Leaf", "priority_score": 8.0, "funding_available_gbp": 300_000_000, "trend_direction": TrendDirection.up},
        {"name": "IoT", "description": "Connected devices, smart cities, industrial IoT, sensor networks, and edge computing. The UK aims to be a global leader in IoT with strong 5G infrastructure investments.", "icon_name": "Wifi", "priority_score": 9.0, "funding_available_gbp": 400_000_000, "trend_direction": TrendDirection.up},
        {"name": "Business", "description": "FinTech, LegalTech, HRTech, productivity tools, and B2B SaaS. London is Europe's leading fintech hub with regulatory sandbox advantages.", "icon_name": "Briefcase", "priority_score": 6.0, "funding_available_gbp": 150_000_000, "trend_direction": TrendDirection.stable},
    ]
    for d in data:
        db.add(Sector(**d))
    db.commit()
    print(f"Seeded {len(data)} sectors.")


# ---- Pre-built idea data (avoids Claude API dependency for seeding) ----

IDEA_TEMPLATES = [
    # Health (sector 1)
    {"sector": "Health", "title": "AI-Powered Early Cancer Detection Platform", "desc": "A cloud-based diagnostic platform using deep learning to analyse medical imaging (MRI, CT, X-ray) for early-stage cancer detection. The system integrates with NHS PACS systems and provides radiologists with AI-generated second opinions, flagging suspicious regions with confidence scores. Built on federated learning principles to train models across multiple NHS trusts without sharing patient data, ensuring GDPR compliance. The platform reduces diagnostic wait times from weeks to hours and improves detection rates by 23% based on pilot studies.", "tech": ["Python", "PyTorch", "DICOM", "FHIR HL7", "AWS SageMaker", "React", "PostgreSQL"], "innovation": 9, "viability": 7, "scalability": 8, "uk_benefit": 9},
    {"sector": "Health", "title": "Remote Patient Monitoring for Chronic Disease Management", "desc": "A wearable-integrated platform that continuously monitors patients with chronic conditions (diabetes, COPD, heart failure) and uses predictive AI to alert clinicians before acute episodes occur. The system connects to NHS GP systems via open APIs and generates personalised care plans. Machine learning models trained on UK Biobank data predict hospitalisation risk 72 hours ahead with 85% accuracy, enabling preventive interventions that reduce A&E admissions by an estimated 30%.", "tech": ["React Native", "Node.js", "TensorFlow", "BLE", "FHIR", "Azure IoT Hub", "MongoDB"], "innovation": 8, "viability": 7, "scalability": 9, "uk_benefit": 9},
    {"sector": "Health", "title": "Mental Health AI Companion for Young Adults", "desc": "A digital mental health support app using conversational AI to provide 24/7 cognitive behavioural therapy (CBT) techniques to young adults aged 16-25. The app integrates with NHS mental health services for escalation pathways and uses sentiment analysis to detect crisis situations. Developed in partnership with UK university counselling services, it addresses the growing mental health crisis with scalable, evidence-based digital interventions.", "tech": ["Flutter", "Python", "Anthropic API", "Firebase", "NLP", "PostgreSQL"], "innovation": 7, "viability": 8, "scalability": 9, "uk_benefit": 8},
    {"sector": "Health", "title": "Blockchain-Enabled Clinical Trial Data Platform", "desc": "A decentralised platform for managing clinical trial data integrity using blockchain technology. Smart contracts automate patient consent tracking, data provenance, and regulatory compliance. The platform reduces clinical trial costs by 40% and time-to-approval by 6 months by eliminating manual audit processes. Designed for UK pharmaceutical companies and CROs, with built-in MHRA regulatory reporting.", "tech": ["Ethereum", "Solidity", "Python", "React", "IPFS", "Docker", "PostgreSQL"], "innovation": 8, "viability": 6, "scalability": 7, "uk_benefit": 7},
    {"sector": "Health", "title": "AI Pharmacogenomics Advisory System", "desc": "A clinical decision support tool that uses genomic data to predict individual patient responses to medications. Integrates with NHS Electronic Health Records to flag potential adverse drug reactions and recommend optimal dosages. The system uses a database of UK-specific pharmacogenomic variants and has been validated against NHS England prescribing data, reducing adverse drug events by an estimated 25%.", "tech": ["Python", "scikit-learn", "FHIR", "Neo4j", "FastAPI", "React", "AWS"], "innovation": 9, "viability": 6, "scalability": 8, "uk_benefit": 8},
    {"sector": "Health", "title": "Smart Wound Care Assessment Platform", "desc": "A mobile application using computer vision to assess wound healing progress through smartphone photographs. The AI model, trained on 500,000 clinical images from UK hospitals, classifies wound types, measures dimensions, and predicts healing trajectories. It generates standardised reports for district nurses, reducing unnecessary clinic visits by 40% and improving chronic wound outcomes. Designed for NHS community care teams.", "tech": ["Python", "TensorFlow", "React Native", "FastAPI", "AWS Rekognition", "PostgreSQL"], "innovation": 8, "viability": 7, "scalability": 8, "uk_benefit": 8},
    {"sector": "Health", "title": "AI-Driven Drug Repurposing Engine", "desc": "A computational platform that uses knowledge graphs and deep learning to identify new therapeutic applications for existing approved drugs. By analysing molecular structures, clinical trial data, and biomedical literature, the system discovers off-label opportunities 10x faster than traditional screening. Initial focus on rare diseases affecting UK populations, with licensing partnerships with UK pharmaceutical firms.", "tech": ["Python", "PyTorch", "Neo4j", "RDKit", "Docker", "React", "Kubernetes"], "innovation": 9, "viability": 6, "scalability": 9, "uk_benefit": 8},
    {"sector": "Health", "title": "NHS Appointment Optimisation with Reinforcement Learning", "desc": "An intelligent scheduling system that uses reinforcement learning to optimise NHS appointment allocation, reducing no-shows and wait times. The system predicts patient behaviour patterns, suggests optimal appointment times, and automates reminders. Piloted across 3 NHS trusts, it achieved a 35% reduction in missed appointments and 20% improvement in clinic utilisation.", "tech": ["Python", "Ray RLlib", "FastAPI", "React", "PostgreSQL", "Redis", "Docker"], "innovation": 7, "viability": 8, "scalability": 9, "uk_benefit": 9},
    # IT (sector 2)
    {"sector": "IT", "title": "Zero-Trust Security Orchestration Platform", "desc": "An enterprise cybersecurity platform implementing zero-trust architecture with AI-driven threat detection and automated incident response. The system continuously verifies every access request, analyses network behaviour patterns, and orchestrates security responses across cloud and on-premise environments. Built for UK critical infrastructure compliance (NIS2 Directive), it reduces mean time to detect threats from 197 days to under 4 hours.", "tech": ["Go", "Python", "Elasticsearch", "Kafka", "React", "Kubernetes", "Terraform"], "innovation": 8, "viability": 8, "scalability": 9, "uk_benefit": 9},
    {"sector": "IT", "title": "Federated AI Model Training Marketplace", "desc": "A decentralised marketplace where organisations can collaboratively train AI models without sharing raw data. Using federated learning and differential privacy, the platform enables UK businesses to build powerful AI models while maintaining data sovereignty and GDPR compliance. Revenue model based on compute credits and model licensing, targeting the £4.7bn UK AI market.", "tech": ["Python", "PyTorch", "gRPC", "Kubernetes", "React", "PostgreSQL", "Blockchain"], "innovation": 9, "viability": 7, "scalability": 9, "uk_benefit": 8},
    {"sector": "IT", "title": "AI Code Review and Vulnerability Detection", "desc": "An AI-powered code analysis platform that automatically reviews pull requests for security vulnerabilities, code quality issues, and compliance with coding standards. Uses large language models fine-tuned on vulnerability databases (CVE, OWASP) and integrates with GitHub, GitLab, and Azure DevOps. Designed for UK government Digital Service Standard compliance.", "tech": ["Python", "Rust", "TypeScript", "LLM", "Docker", "PostgreSQL", "GraphQL"], "innovation": 8, "viability": 8, "scalability": 9, "uk_benefit": 7},
    {"sector": "IT", "title": "Quantum-Resistant Encryption Toolkit", "desc": "A developer toolkit providing quantum-resistant cryptographic primitives for UK businesses preparing for the post-quantum era. Implements NIST-approved algorithms (CRYSTALS-Kyber, CRYSTALS-Dilithium) with easy-to-use APIs and migration tools for existing systems. Includes compliance checking against NCSC guidelines and automated certificate management.", "tech": ["Rust", "C++", "Python", "WebAssembly", "OpenSSL", "Docker", "React"], "innovation": 9, "viability": 7, "scalability": 8, "uk_benefit": 9},
    {"sector": "IT", "title": "Autonomous DevOps Agent Platform", "desc": "An AI agent that autonomously manages cloud infrastructure, deploys applications, monitors performance, and resolves incidents without human intervention. Using reinforcement learning trained on operational data from UK enterprises, it reduces MTTR by 80% and infrastructure costs by 35%. Supports multi-cloud environments (AWS, Azure, GCP) with UK data residency guarantees.", "tech": ["Python", "Go", "Terraform", "Kubernetes", "Prometheus", "React", "PostgreSQL", "LangChain"], "innovation": 9, "viability": 7, "scalability": 9, "uk_benefit": 7},
    {"sector": "IT", "title": "Privacy-Preserving Data Analytics Platform", "desc": "A secure multi-party computation platform enabling UK organisations to perform joint analytics on sensitive datasets without revealing underlying data. Uses homomorphic encryption and secure enclaves to process financial, healthcare, and government data collaboratively. Compliant with UK Data Protection Act 2018 and designed for cross-sector data sharing initiatives.", "tech": ["Rust", "Python", "Intel SGX", "React", "PostgreSQL", "gRPC", "Docker"], "innovation": 9, "viability": 6, "scalability": 8, "uk_benefit": 9},
    {"sector": "IT", "title": "Natural Language Database Query Interface", "desc": "An AI-powered tool that lets non-technical business users query complex databases using natural language. The system translates English questions into optimised SQL, visualises results, and learns from user feedback. Reduces dependency on data engineering teams and democratises data access across UK enterprises, with built-in data governance and audit trails.", "tech": ["Python", "LLM", "FastAPI", "React", "PostgreSQL", "Docker", "Elasticsearch"], "innovation": 7, "viability": 8, "scalability": 8, "uk_benefit": 7},
    {"sector": "IT", "title": "AI-Powered Accessibility Compliance Auditor", "desc": "An automated web accessibility testing platform that uses computer vision and NLP to audit websites against WCAG 2.2 and UK Public Sector Bodies Accessibility Regulations 2018. Goes beyond rule-based checkers by simulating user journeys with assistive technologies and generating detailed remediation reports with code-level fixes.", "tech": ["Python", "Playwright", "TensorFlow", "React", "Node.js", "PostgreSQL", "Docker"], "innovation": 8, "viability": 8, "scalability": 9, "uk_benefit": 8},
    {"sector": "IT", "title": "Real-Time AI Translation Platform for UK Public Services", "desc": "A specialised machine translation platform optimised for UK public service contexts (courts, councils, hospitals). Supports 50+ languages with domain-specific fine-tuning for legal, medical, and administrative terminology. Includes real-time speech translation for face-to-face interactions and document translation with certified accuracy levels.", "tech": ["Python", "Transformer Models", "FastAPI", "React", "WebRTC", "PostgreSQL", "Kubernetes"], "innovation": 7, "viability": 8, "scalability": 9, "uk_benefit": 9},
    # Ecommerce (sector 3)
    {"sector": "Ecommerce", "title": "AI-Powered Sustainable Fashion Marketplace", "desc": "A curated online marketplace connecting UK consumers with sustainable fashion brands, powered by AI that analyses supply chain transparency, material sourcing, and carbon footprints. Features virtual try-on using AR, personalised style recommendations, and a carbon offset calculator. Addresses the £60bn UK fashion market's shift toward sustainability.", "tech": ["Next.js", "Python", "TensorFlow", "Three.js", "Stripe", "PostgreSQL", "Redis"], "innovation": 7, "viability": 8, "scalability": 8, "uk_benefit": 7},
    {"sector": "Ecommerce", "title": "Hyper-Personalised Product Discovery Engine", "desc": "An AI recommendation engine using graph neural networks to model complex customer-product relationships beyond simple collaborative filtering. Processes browsing behaviour, purchase history, social signals, and contextual data (weather, events, trends) to surface products with 3x higher conversion rates. B2B SaaS model targeting UK mid-market retailers.", "tech": ["Python", "PyTorch Geometric", "FastAPI", "React", "Redis", "Elasticsearch", "Kafka"], "innovation": 8, "viability": 8, "scalability": 9, "uk_benefit": 7},
    {"sector": "Ecommerce", "title": "Automated Returns Fraud Detection System", "desc": "An ML system that analyses return patterns, customer behaviour, and product data to detect and prevent returns fraud, which costs UK retailers £7bn annually. Uses anomaly detection and network analysis to identify serial returners, wardrobing, and receipt fraud while maintaining legitimate customer experience. Integrates with major UK ecommerce platforms via API.", "tech": ["Python", "scikit-learn", "FastAPI", "React", "PostgreSQL", "Kafka", "Docker"], "innovation": 7, "viability": 9, "scalability": 8, "uk_benefit": 8},
    {"sector": "Ecommerce", "title": "Voice Commerce Platform for Elderly Consumers", "desc": "A voice-first shopping platform designed for elderly and accessibility-challenged consumers in the UK. Uses conversational AI to navigate product catalogues, place orders, and manage deliveries through smart speakers and phones. Integrates with major UK grocery chains and pharmacies, addressing the £14bn spending power of the 65+ demographic.", "tech": ["Python", "Alexa SDK", "Node.js", "React", "Stripe", "PostgreSQL", "NLP"], "innovation": 8, "viability": 7, "scalability": 7, "uk_benefit": 8},
    {"sector": "Ecommerce", "title": "Cross-Border Trade Compliance Automation", "desc": "A platform automating customs declarations, tariff calculations, and regulatory compliance for UK-EU cross-border ecommerce post-Brexit. Uses NLP to classify products against HS codes, calculates duties and VAT in real-time, and generates required documentation. Targets the 250,000+ UK SMEs affected by new trade barriers.", "tech": ["Python", "FastAPI", "React", "PostgreSQL", "Elasticsearch", "AWS Lambda", "Docker"], "innovation": 7, "viability": 9, "scalability": 8, "uk_benefit": 9},
    {"sector": "Ecommerce", "title": "Social Commerce Analytics Dashboard", "desc": "An analytics platform that tracks social media-driven commerce across TikTok Shop, Instagram, and Facebook Marketplace for UK brands. Uses NLP to analyse sentiment, predict viral trends, and optimise content strategies. Provides attribution modelling showing the full customer journey from social discovery to purchase, helping brands allocate marketing budgets effectively.", "tech": ["Python", "React", "Node.js", "PostgreSQL", "Elasticsearch", "TensorFlow", "Grafana"], "innovation": 7, "viability": 8, "scalability": 8, "uk_benefit": 6},
    # Agriculture (sector 4)
    {"sector": "Agriculture", "title": "Precision Livestock Health Monitoring with IoT", "desc": "A smart farming solution using IoT collar sensors and computer vision to monitor livestock health, detect early disease symptoms, and optimise feeding schedules. Machine learning models predict illness 48 hours before clinical signs appear, reducing antibiotic use by 30% and mortality by 15%. Designed for UK dairy and beef farms, integrating with DEFRA reporting systems.", "tech": ["Python", "TensorFlow", "LoRaWAN", "React", "TimescaleDB", "Edge AI", "Docker"], "innovation": 8, "viability": 7, "scalability": 8, "uk_benefit": 8},
    {"sector": "Agriculture", "title": "AI-Optimised Vertical Farming Management", "desc": "A complete vertical farming operating system that uses reinforcement learning to optimise growing conditions (light spectrum, nutrients, temperature, humidity) for maximum yield and minimum energy consumption. The platform reduces water usage by 95% and energy costs by 40% compared to conventional vertical farms. Targeting the UK's £1.5bn controlled environment agriculture market.", "tech": ["Python", "Ray RLlib", "React", "Node.js", "InfluxDB", "MQTT", "Docker", "Raspberry Pi"], "innovation": 9, "viability": 7, "scalability": 8, "uk_benefit": 8},
    {"sector": "Agriculture", "title": "Blockchain Farm-to-Fork Supply Chain Tracker", "desc": "A supply chain transparency platform using blockchain and IoT to track food products from UK farms to consumer plates. QR codes on products reveal complete provenance data, environmental impact scores, and food safety certifications. Helps UK retailers meet new supply chain due diligence regulations and consumer demand for transparency.", "tech": ["Hyperledger Fabric", "Node.js", "React", "IoT Sensors", "PostgreSQL", "Docker", "NFC"], "innovation": 7, "viability": 7, "scalability": 8, "uk_benefit": 8},
    {"sector": "Agriculture", "title": "Drone-Based Crop Disease Detection Service", "desc": "An autonomous drone fleet service that surveys UK farmland using multispectral imaging and AI to detect crop diseases, nutrient deficiencies, and pest infestations at early stages. The platform generates prescription maps for targeted treatment, reducing pesticide use by 50% and increasing yields by 15%. Subscription model for UK arable farmers.", "tech": ["Python", "TensorFlow", "ROS", "React", "PostGIS", "Docker", "AWS S3", "OpenCV"], "innovation": 8, "viability": 7, "scalability": 7, "uk_benefit": 8},
    {"sector": "Agriculture", "title": "Carbon Credit Marketplace for UK Farmers", "desc": "A digital marketplace enabling UK farmers to quantify, verify, and trade carbon credits from regenerative farming practices. Uses satellite imagery and soil sensors to measure carbon sequestration with scientific rigour. Connects farmers with corporations seeking verified UK carbon offsets, creating a new revenue stream for the agricultural sector.", "tech": ["Python", "React", "Satellite API", "IoT Sensors", "Blockchain", "PostgreSQL", "FastAPI"], "innovation": 8, "viability": 7, "scalability": 8, "uk_benefit": 9},
    {"sector": "Agriculture", "title": "AI Crop Yield Prediction and Insurance Platform", "desc": "A parametric insurance platform for UK farmers that uses satellite data, weather models, and historical yield data to predict crop outcomes and automatically trigger payouts when conditions indicate losses. Eliminates lengthy claims processes and provides affordable coverage to small farms. Uses ensemble ML models achieving 90% prediction accuracy.", "tech": ["Python", "XGBoost", "Satellite API", "React", "FastAPI", "PostgreSQL", "Stripe"], "innovation": 8, "viability": 7, "scalability": 8, "uk_benefit": 8},
    # IoT (sector 5)
    {"sector": "IoT", "title": "Smart Building Energy Management System", "desc": "An IoT platform that optimises energy consumption in commercial buildings using sensor networks, digital twins, and reinforcement learning. The system integrates with BMS (Building Management Systems), analyses occupancy patterns, weather forecasts, and energy prices to reduce consumption by 35% and carbon emissions by 40%. Aligned with UK Net Zero 2050 targets.", "tech": ["Python", "Digital Twin", "MQTT", "React", "InfluxDB", "TensorFlow", "Docker", "Kubernetes"], "innovation": 8, "viability": 8, "scalability": 9, "uk_benefit": 9},
    {"sector": "IoT", "title": "Connected Water Network Leak Detection", "desc": "An AI-powered acoustic sensor network that detects and precisely locates water leaks in UK municipal pipe networks. Uses edge AI to process sensor data in real-time, reducing water wastage (currently 3 billion litres/day in the UK) by 50%. The platform integrates with water company SCADA systems and generates automated repair work orders.", "tech": ["Edge AI", "LoRaWAN", "Python", "React", "TimescaleDB", "Docker", "MQTT", "TensorFlow Lite"], "innovation": 8, "viability": 8, "scalability": 8, "uk_benefit": 9},
    {"sector": "IoT", "title": "Industrial Predictive Maintenance Platform", "desc": "A vibration and acoustic sensor platform using edge ML to predict equipment failures in UK manufacturing plants 2-4 weeks in advance. The system reduces unplanned downtime by 75% and maintenance costs by 30%. Integrates with ERP systems (SAP, Oracle) and provides a digital twin of the factory floor for simulation.", "tech": ["Python", "Edge AI", "React", "MQTT", "InfluxDB", "TensorFlow Lite", "Docker", "Node-RED"], "innovation": 7, "viability": 8, "scalability": 8, "uk_benefit": 8},
    {"sector": "IoT", "title": "Smart Traffic Management for UK Cities", "desc": "An adaptive traffic control system using IoT sensors, camera feeds, and reinforcement learning to optimise traffic flow in real-time. Reduces average commute times by 20% and vehicle emissions by 15% in urban areas. Integrates with emergency services for priority routing and provides open data feeds for city planning. Piloted with Transport for London.", "tech": ["Python", "Computer Vision", "RL", "React", "PostGIS", "Kafka", "Docker", "NVIDIA Jetson"], "innovation": 8, "viability": 7, "scalability": 8, "uk_benefit": 9},
    {"sector": "IoT", "title": "Elderly Care Smart Home Platform", "desc": "A non-intrusive IoT monitoring system for elderly people living independently. Uses ambient sensors (motion, door, appliance usage) and AI to learn daily routines, detect anomalies (falls, missed medications, unusual inactivity), and alert caregivers. Integrates with NHS social care teams and reduces care home admissions. Privacy-preserving design with no cameras.", "tech": ["Zigbee", "Python", "TensorFlow Lite", "React Native", "MQTT", "PostgreSQL", "Docker"], "innovation": 7, "viability": 8, "scalability": 8, "uk_benefit": 9},
    {"sector": "IoT", "title": "Air Quality Monitoring Network for Schools", "desc": "A low-cost IoT sensor network measuring indoor and outdoor air quality at UK schools. Monitors PM2.5, CO2, NO2, VOCs, temperature, and humidity. AI models predict pollution episodes and automatically activate ventilation. Dashboard for parents and local authorities. Addresses growing concern about air quality impact on children's health and academic performance.", "tech": ["Arduino", "Python", "React", "InfluxDB", "MQTT", "Grafana", "Docker", "LoRaWAN"], "innovation": 7, "viability": 8, "scalability": 9, "uk_benefit": 9},
    # Business (sector 6)
    {"sector": "Business", "title": "AI Contract Analysis and Risk Scoring", "desc": "A LegalTech platform using NLP to automatically review contracts, identify risky clauses, and ensure compliance with UK regulations. The system analyses contracts 100x faster than manual review, scores risk levels, and suggests amendments. Built with UK-specific legal knowledge including Companies Act 2006, GDPR, and employment law.", "tech": ["Python", "LLM", "FastAPI", "React", "Elasticsearch", "PostgreSQL", "Docker"], "innovation": 7, "viability": 8, "scalability": 9, "uk_benefit": 7},
    {"sector": "Business", "title": "Open Banking Personal Finance AI Advisor", "desc": "A PSD2-compliant personal finance platform that aggregates UK bank accounts, analyses spending patterns, and provides AI-powered financial advice. Uses reinforcement learning to optimise savings strategies, find better deals, and automate investments. Targets the 40% of UK adults who don't have a financial plan. Revenue from premium features and affiliate partnerships.", "tech": ["Python", "React", "Open Banking API", "PostgreSQL", "TensorFlow", "Plaid", "Stripe"], "innovation": 7, "viability": 8, "scalability": 9, "uk_benefit": 8},
    {"sector": "Business", "title": "SME Grant Application Automation Tool", "desc": "An AI platform that matches UK SMEs with relevant government grants, auto-fills applications using company data, and optimises submissions using NLP analysis of successful past applications. Addresses the £2bn in unclaimed government grants annually. Integrates with Companies House, HMRC data, and major grant portals.", "tech": ["Python", "LLM", "FastAPI", "React", "PostgreSQL", "Elasticsearch", "Companies House API"], "innovation": 8, "viability": 8, "scalability": 8, "uk_benefit": 9},
    {"sector": "Business", "title": "AI-Powered Employee Retention Predictor", "desc": "An HR analytics platform using ML to predict employee flight risk and recommend personalised retention strategies. Analyses anonymised data from surveys, performance reviews, and market salary benchmarks. Helps UK businesses reduce the £4bn annual cost of employee turnover. GDPR-compliant with differential privacy guarantees.", "tech": ["Python", "scikit-learn", "FastAPI", "React", "PostgreSQL", "Docker", "Tableau"], "innovation": 7, "viability": 8, "scalability": 8, "uk_benefit": 7},
    {"sector": "Business", "title": "Regulatory Change Intelligence Platform", "desc": "An AI-powered monitoring system that tracks UK regulatory changes (FCA, PRA, HMRC, ICO), assesses impact on specific businesses, and generates compliance action plans. Uses NLP to parse legislation, regulatory guidance, and consultation papers, alerting compliance teams to relevant changes before deadlines. Critical for post-Brexit regulatory divergence monitoring.", "tech": ["Python", "NLP", "FastAPI", "React", "Elasticsearch", "PostgreSQL", "Docker", "Kafka"], "innovation": 8, "viability": 8, "scalability": 8, "uk_benefit": 8},
    {"sector": "Business", "title": "Automated VAT Compliance for Cross-Border B2B", "desc": "A FinTech platform automating VAT compliance for UK businesses trading internationally. Handles new post-Brexit VAT rules, reverse charge mechanisms, and digital services tax across 100+ jurisdictions. Integrates with accounting software (Xero, QuickBooks, Sage) and submits Making Tax Digital returns automatically.", "tech": ["Python", "FastAPI", "React", "PostgreSQL", "Xero API", "Stripe", "Docker", "AWS Lambda"], "innovation": 7, "viability": 9, "scalability": 8, "uk_benefit": 8},
    {"sector": "Business", "title": "AI Meeting Summariser and Action Tracker", "desc": "An enterprise tool that records meetings, generates accurate transcriptions using speech recognition, summarises key decisions, and automatically creates action items assigned to participants. Supports multiple accents and technical jargon common in UK business settings. Integrates with Teams, Slack, and Jira.", "tech": ["Python", "Whisper", "LLM", "FastAPI", "React", "PostgreSQL", "WebSocket", "Docker"], "innovation": 6, "viability": 9, "scalability": 9, "uk_benefit": 6},
    {"sector": "Business", "title": "Supplier ESG Risk Assessment Engine", "desc": "A B2B platform that automatically assesses environmental, social, and governance risks across supply chains using public data, news analysis, and satellite imagery. Helps UK companies comply with upcoming mandatory ESG reporting requirements. Scores suppliers on 50+ ESG metrics and generates board-ready reports.", "tech": ["Python", "NLP", "React", "PostgreSQL", "Satellite API", "FastAPI", "Docker", "Elasticsearch"], "innovation": 8, "viability": 7, "scalability": 8, "uk_benefit": 8},
]


def seed_ideas(db):
    if db.query(Idea).count() > 0:
        print("Ideas already seeded, skipping.")
        return

    sectors = {s.name: s.id for s in db.query(Sector).all()}

    for t in IDEA_TEMPLATES:
        sid = sectors.get(t["sector"], 1)
        prob = round(
            t["innovation"] * 0.30 + t["viability"] * 0.30 +
            t["scalability"] * 0.25 + t.get("uk_benefit", 7) * 0.15, 1
        ) * 10  # scale to 0-100
        prob = min(prob, 95)

        idea = Idea(
            sector_id=sid,
            title=t["title"],
            description=t["desc"],
            tech_stack=t["tech"],
            innovation_score=float(t["innovation"]),
            viability_score=float(t["viability"]),
            scalability_score=float(t["scalability"]),
            uk_benefit_score=float(t.get("uk_benefit", 7)),
            overall_probability=prob,
            market_size_gbp=random.randint(10_000_000, 500_000_000),
            job_creation_potential={"year_1": random.randint(2, 10), "year_2": random.randint(5, 25), "year_3": random.randint(10, 50)},
        )
        db.add(idea)

    db.commit()
    print(f"Seeded {len(IDEA_TEMPLATES)} ideas.")


# ---- Document content for RAG corpus ----

DOCUMENT_CONTENT = [
    # Funded projects
    {"title": "AI-Driven Sepsis Early Warning System - UKRI Funded Project", "content": "This Innovate UK-funded project developed an AI system that analyses real-time patient data from hospital monitors to predict sepsis onset 6 hours before clinical diagnosis. The system was deployed across 5 NHS trusts and demonstrated a 32% reduction in sepsis mortality. Total funding: £2.4 million. Lead: University of Oxford in partnership with Sensyne Health. The project used federated learning to train models across hospital sites without sharing patient data, addressing key GDPR concerns. The system integrates with existing NHS electronic health record systems and provides alerts through the hospital's standard monitoring dashboards.", "doc_type": DocType.funded_project, "sector": "Health"},
    {"title": "Quantum Computing Algorithms for Drug Discovery - InnovateUK", "content": "A £3.2 million Innovate UK project exploring quantum computing applications in pharmaceutical research. The consortium led by Cambridge Quantum Computing developed hybrid quantum-classical algorithms that simulate molecular interactions 1000x faster than classical methods. The project identified 3 novel drug candidates for rare diseases and established a framework for UK pharmaceutical companies to access quantum computing resources through a cloud platform.", "doc_type": DocType.funded_project, "sector": "IT"},
    {"title": "Autonomous Last-Mile Delivery Robot Fleet - UK Innovation Fund", "content": "This project received £1.8 million from the UK Innovation Fund to develop and trial autonomous delivery robots in Milton Keynes and Northampton. The robots use LiDAR, computer vision, and path planning algorithms to navigate pavements safely. The trial delivered 50,000 parcels over 12 months with a 99.7% success rate, demonstrating viability for UK urban environments.", "doc_type": DocType.funded_project, "sector": "Ecommerce"},
    {"title": "Regenerative Agriculture Carbon Measurement Platform", "content": "Funded by UKRI with £1.5 million, this project created a digital platform for measuring and verifying soil carbon sequestration on UK farms. Using satellite imagery, IoT soil sensors, and machine learning models, the platform provides accurate carbon stock assessments at scale. The project involved 200 farms across England and Wales and established methodologies now adopted by the UK voluntary carbon credit market.", "doc_type": DocType.funded_project, "sector": "Agriculture"},
    {"title": "5G-Enabled Smart Factory Demonstrator - DCMS Fund", "content": "A £4.1 million project funded by DCMS deploying 5G-connected IoT sensors across a UK manufacturing facility. The demonstrator showed how real-time data analytics and digital twins can improve productivity by 25% and reduce energy consumption by 20%. The project created a replicable framework for UK manufacturers transitioning to Industry 4.0.", "doc_type": DocType.funded_project, "sector": "IoT"},
    {"title": "Open Banking Data Sharing Framework for SMEs", "content": "This £900,000 Innovate UK project developed secure data sharing protocols enabling UK SMEs to share financial data with lenders, insurers, and government agencies. The framework reduced loan application processing time from 3 weeks to 48 hours for participating businesses. The project involved 15 UK banks and demonstrated how open banking infrastructure can improve SME access to finance.", "doc_type": DocType.funded_project, "sector": "Business"},
    {"title": "NHS AI Triage System for Emergency Departments", "content": "A £2.8 million UKRI-funded project implementing an AI-powered triage system across 8 NHS emergency departments. The system analyses patient symptoms, vital signs, and historical data to prioritise cases and predict department capacity needs. Results showed 28% reduction in waiting times and 15% improvement in resource allocation during peak hours.", "doc_type": DocType.funded_project, "sector": "Health"},
    {"title": "Cybersecurity AI for Critical National Infrastructure", "content": "This £5.2 million project from the National Cyber Security Centre developed AI systems to detect and respond to cyber attacks on UK critical infrastructure including energy grids and water systems. The platform uses behavioural analysis and anomaly detection to identify threats in real-time, reducing response time from hours to seconds.", "doc_type": DocType.funded_project, "sector": "IT"},
    {"title": "Sustainable Packaging Innovation Challenge - Winner", "content": "Winner of the £2 million Innovate UK Sustainable Packaging Challenge, this project developed compostable packaging made from seaweed and agricultural waste. The material decomposes in 6 weeks and can replace plastic packaging for 80% of supermarket products. The technology is now being scaled for UK-wide deployment with Tesco and Sainsbury's.", "doc_type": DocType.funded_project, "sector": "Ecommerce"},
    {"title": "Autonomous Farm Robot for Precision Weeding", "content": "This £1.3 million Innovate UK project developed an autonomous robot using computer vision to identify and remove weeds without herbicides. The robot achieved 95% weed identification accuracy and reduced herbicide use by 90% in trials across 15 UK farms. The system is particularly effective for organic farming operations.", "doc_type": DocType.funded_project, "sector": "Agriculture"},
    {"title": "Smart Grid Demand Response System", "content": "A £3.5 million UKRI project creating an IoT-based demand response platform for UK households. The system uses smart meters, connected appliances, and AI to automatically shift electricity consumption to off-peak times, reducing household energy costs by 25% and supporting grid stability. Piloted with 10,000 UK homes.", "doc_type": DocType.funded_project, "sector": "IoT"},
    {"title": "Digital Identity Verification for Financial Services", "content": "This £1.7 million FCA-backed innovation project developed AI-powered identity verification reducing KYC processing time from 3 days to 15 minutes. Using facial recognition, document verification, and liveness detection, the system meets FCA compliance requirements while improving customer onboarding conversion by 40%.", "doc_type": DocType.funded_project, "sector": "Business"},
    {"title": "Genomics England Clinical Decision Support Tool", "content": "A £2.1 million project building AI tools that help NHS clinicians interpret genomic test results for cancer patients. The system cross-references patient genomic data with clinical trial databases and drug response data to recommend personalised treatment plans. Deployed across 4 NHS Genomic Medicine Service Alliance hubs.", "doc_type": DocType.funded_project, "sector": "Health"},
    {"title": "Edge Computing Platform for Rural Connectivity", "content": "Funded with £2.9 million from DCMS, this project deployed edge computing nodes across rural UK areas with poor connectivity. The platform enables local AI processing for agricultural IoT devices, telehealth services, and smart village applications without depending on cloud connectivity. Covers 500 square miles of rural Wales.", "doc_type": DocType.funded_project, "sector": "IoT"},
    {"title": "AI-Powered Trade Finance Platform", "content": "This £1.4 million Innovate UK project created an AI platform automating trade finance document processing for UK exporters. Using NLP to extract and verify information from letters of credit, bills of lading, and customs declarations, the system reduces processing time by 80% and errors by 95%.", "doc_type": DocType.funded_project, "sector": "Business"},
    {"title": "Vertical Farming Nutrient Optimisation Using ML", "content": "A £1.1 million UKRI-funded project using machine learning to optimise nutrient delivery in vertical farms. The system analyses plant growth data from sensors and cameras to adjust nutrient solutions in real-time, increasing yield by 30% and reducing nutrient waste by 45%. Tested at growing facilities in Lincolnshire and Kent.", "doc_type": DocType.funded_project, "sector": "Agriculture"},
    {"title": "Smart Motorway Safety Enhancement System", "content": "This £4.5 million Highways England project deployed IoT sensors and AI along 30 miles of smart motorway to detect stopped vehicles, debris, and pedestrians in real-time. The system reduced detection time from 17 minutes to under 20 seconds, addressing public safety concerns about smart motorways.", "doc_type": DocType.funded_project, "sector": "IoT"},
    {"title": "B2B Marketplace for Circular Economy Materials", "content": "Funded with £800,000 by Innovate UK, this platform connects UK manufacturers to trade waste materials and by-products. AI matching algorithms pair waste producers with potential users, creating circular supply chains. The platform diverted 50,000 tonnes of material from landfill in its first year.", "doc_type": DocType.funded_project, "sector": "Ecommerce"},
    {"title": "Natural Language Processing for Legal Document Analysis", "content": "A £1.6 million Innovate UK project developing NLP tools for automating legal document review in UK law firms. The system analyses contracts, case law, and regulatory documents with 97% accuracy, reducing junior lawyer review time by 70%. Now used by 20 UK law firms including Magic Circle firms.", "doc_type": DocType.funded_project, "sector": "Business"},
    {"title": "Wearable Biosensor for Workplace Health Monitoring", "content": "This £1.2 million UKRI project developed a non-invasive wearable sensor measuring stress levels, hydration, and fatigue in workplace environments. The system uses AI to predict burnout risk and suggests interventions. Trialled across 5 UK companies with 2,000 employees, demonstrating 20% reduction in sick days.", "doc_type": DocType.funded_project, "sector": "Health"},
    # Additional funded projects
    {"title": "Explainable AI for NHS Clinical Decisions", "content": "A £2.3 million UKRI project developing explainable AI methods for clinical decision support in the NHS. The research created novel techniques that allow AI recommendations to be understood and trusted by clinicians, addressing a key barrier to AI adoption in healthcare. The tools were validated across 6 clinical pathways.", "doc_type": DocType.funded_project, "sector": "Health"},
    {"title": "Green Hydrogen Production Optimisation", "content": "This £3.8 million Innovate UK project used IoT sensors and AI to optimise green hydrogen production from renewable energy sources. The system improved electrolysis efficiency by 18% and reduced production costs by 25%, making green hydrogen more competitive for UK industrial decarbonisation.", "doc_type": DocType.funded_project, "sector": "IoT"},
    {"title": "AI Supply Chain Resilience Platform", "content": "Funded with £1.9 million by Innovate UK, this project created an AI platform that predicts supply chain disruptions for UK manufacturers. Using satellite data, news analysis, and trade data, the system provides 2-4 week advance warning of potential disruptions, allowing companies to adjust sourcing strategies.", "doc_type": DocType.funded_project, "sector": "Business"},
    {"title": "Microbiome Analysis Platform for Precision Agriculture", "content": "A £1.4 million BBSRC project developing AI tools for analysing soil microbiome data to optimise crop treatments. The platform sequences soil DNA samples and recommends beneficial microbial treatments, reducing chemical fertiliser use by 40% while maintaining yields on UK arable farms.", "doc_type": DocType.funded_project, "sector": "Agriculture"},
    {"title": "Computer Vision for Retail Shelf Analytics", "content": "This £950,000 Innovate UK project developed computer vision technology for automated retail shelf monitoring. Cameras and edge AI detect stockouts, misplaced products, and planogram compliance in real-time, helping UK retailers reduce lost sales by 15% and improve store operations.", "doc_type": DocType.funded_project, "sector": "Ecommerce"},
    {"title": "Federated Learning for Financial Fraud Detection", "content": "A £2.7 million FCA Innovation Pathways project developing federated learning systems that allow UK banks to collaboratively train fraud detection models without sharing customer data. The system improved fraud detection rates by 45% compared to individual bank models.", "doc_type": DocType.funded_project, "sector": "IT"},
    {"title": "Smart Parking IoT Network for UK Cities", "content": "This £1.6 million project deployed ground sensors and AI across 5 UK cities to guide drivers to available parking spaces via a mobile app. The system reduced parking search time by 40%, cutting urban emissions and congestion. Revenue shared between councils and the technology provider.", "doc_type": DocType.funded_project, "sector": "IoT"},
    {"title": "AI-Powered Patent Analysis for R&D Teams", "content": "Funded with £1.1 million by Innovate UK, this project created NLP tools for analysing the global patent landscape to help UK R&D teams identify innovation opportunities and freedom-to-operate risks. The platform processes 100 million patents and provides competitive intelligence dashboards.", "doc_type": DocType.funded_project, "sector": "IT"},
    {"title": "Automated Greenhouse Climate Control", "content": "A £800,000 UKRI project using reinforcement learning to control greenhouse environments for optimal crop growth. The AI system manages heating, ventilation, lighting, and irrigation simultaneously, reducing energy costs by 35% while increasing tomato yields by 22% in UK commercial greenhouses.", "doc_type": DocType.funded_project, "sector": "Agriculture"},
    {"title": "Digital Therapeutics Platform for Musculoskeletal Conditions", "content": "This £1.8 million NIHR-funded project developed a digital therapeutics app using AI to personalise exercise programmes for patients with chronic back pain and arthritis. The app uses pose estimation to ensure correct exercise form and adapts programmes based on progress. NHS pilots showed 40% improvement in patient outcomes.", "doc_type": DocType.funded_project, "sector": "Health"},
    # News articles
    {"title": "UK AI Sector Reaches £21 Billion Valuation", "content": "The UK artificial intelligence sector has reached a combined valuation of £21 billion, making it the third largest AI ecosystem globally after the US and China. The government's AI Strategy published alongside increased R&D tax credits has attracted significant investment, with London-based AI startups raising £3.4 billion in the past year alone. Key growth areas include healthcare AI, autonomous systems, and natural language processing. The Alan Turing Institute reports that 1,300 new AI companies were founded in the UK last year, creating 50,000 high-skilled jobs.", "doc_type": DocType.news, "sector": "IT"},
    {"title": "Innovate UK Launches £100 Million Green Innovation Fund", "content": "Innovate UK has announced a new £100 million fund specifically targeting green technology innovations. The fund will support projects in clean energy, sustainable agriculture, circular economy, and green transport. Applications are open to UK-registered companies and academic institutions. Priority areas include carbon capture, hydrogen production, and nature-based solutions. The fund forms part of the government's commitment to reaching net zero by 2050 and maintaining the UK's position as a global leader in green finance and technology.", "doc_type": DocType.news, "sector": "Agriculture"},
    {"title": "UK FinTech Sector Employs Over 76,000 People", "content": "New data from Innovate Finance shows the UK FinTech sector now employs over 76,000 people, with revenue exceeding £11 billion annually. London remains the European fintech capital, but significant clusters are growing in Leeds, Edinburgh, Manchester, and Bristol. Key trends include embedded finance, open banking adoption reaching 7 million users, and AI-powered compliance tools. The FCA's regulatory sandbox has been cited as a key competitive advantage.", "doc_type": DocType.news, "sector": "Business"},
    {"title": "NHS Digital Transformation Accelerates Post-Pandemic", "content": "NHS digital transformation spending has increased by 40% year-on-year, with major investments in electronic health records, telemedicine platforms, and AI diagnostic tools. Over 70% of GP consultations now offer digital options, and NHS trusts are piloting AI-assisted radiology in 20 hospitals. The NHS AI Lab has approved 15 AI medical devices for deployment, focusing on early cancer detection and stroke identification.", "doc_type": DocType.news, "sector": "Health"},
    {"title": "UK E-commerce Market to Exceed £150 Billion", "content": "The UK e-commerce market is projected to exceed £150 billion in annual sales, representing 30% of all retail transactions. Key drivers include mobile commerce growth (45% of transactions), social commerce expansion, and improved delivery logistics. Quick commerce (under 15-minute delivery) is the fastest-growing segment, with UK-based startups raising £500 million in funding. Sustainability-focused e-commerce platforms are gaining market share as consumers demand eco-friendly options.", "doc_type": DocType.news, "sector": "Ecommerce"},
    {"title": "UK Smart City Investment Reaches £2.3 Billion", "content": "UK cities have collectively invested £2.3 billion in smart city technologies including IoT infrastructure, 5G networks, and AI-powered urban management systems. Manchester, Birmingham, and Bristol lead adoption with comprehensive smart city strategies. Key projects include intelligent transport systems, environmental monitoring networks, and digital citizen services. The government's Connected Places Catapult is coordinating national standards.", "doc_type": DocType.news, "sector": "IoT"},
    {"title": "UK AgriTech Funding Doubles to £600 Million", "content": "Investment in UK agricultural technology has doubled to £600 million, driven by food security concerns, net zero commitments, and post-Brexit agricultural policy reform. Key areas attracting funding include precision farming, vertical agriculture, alternative proteins, and farm management software. The government's AgriTech Strategy prioritises technology adoption among smaller farms through grants and training programmes.", "doc_type": DocType.news, "sector": "Agriculture"},
    {"title": "Cybersecurity Skills Gap Widens to 14,000 Unfilled Roles", "content": "The UK cybersecurity sector faces a skills gap of 14,000 unfilled positions despite the industry growing to £10.5 billion. New initiatives including the CyberFirst programme and university partnerships aim to address the shortage. AI-powered security tools are increasingly filling the gap, with UK companies developing automated threat detection and response systems that reduce the need for manual analysis.", "doc_type": DocType.news, "sector": "IT"},
    {"title": "UK Healthtech Investment Hits Record £4.2 Billion", "content": "UK healthtech companies raised a record £4.2 billion in funding, with digital health, AI diagnostics, and genomics leading the way. The UK's life sciences sector strategy and regulatory fast-track pathways have attracted global pharmaceutical companies to establish AI research centres in the UK. Notable deals include Babylon Health's NHS contracts and BenevolentAI's drug discovery partnerships.", "doc_type": DocType.news, "sector": "Health"},
    {"title": "UKRI Reports 30% Increase in Innovation Grant Applications", "content": "UK Research and Innovation reports a 30% year-on-year increase in innovation grant applications, reflecting growing entrepreneurial activity. The most popular funding schemes include Smart Grants (up to £500,000 for any innovative project) and sector-specific challenges. Success rates average 12%, with healthtech, AI, and clean energy proposals performing best. UKRI has streamlined the application process and introduced a new fast-track scheme for repeat applicants.", "doc_type": DocType.news, "sector": "Business"},
    {"title": "5G Rollout Enables New IoT Applications Across UK", "content": "The UK's 5G network now covers 50% of the population, enabling new IoT applications in healthcare, manufacturing, and agriculture. Industrial 5G deployments are showing productivity gains of 15-30% in early adopter factories. The government's 5G Innovation Regions programme has funded 20 test beds exploring applications from remote surgery to autonomous vehicles.", "doc_type": DocType.news, "sector": "IoT"},
    {"title": "UK Startup Ecosystem Ranked 4th Globally", "content": "The UK startup ecosystem has been ranked 4th globally by Startup Genome, with London maintaining its position as Europe's leading tech hub. The UK produced 15 new unicorns in the past year, with a total of 130 companies valued at over $1 billion. Key strengths include access to talent, regulatory frameworks, and proximity to European markets. Government initiatives like the Seed Enterprise Investment Scheme continue to drive early-stage funding.", "doc_type": DocType.news, "sector": "Business"},
    {"title": "Precision Medicine Pilot Shows 50% Better Patient Outcomes", "content": "An NHS England pilot programme using precision medicine approaches showed 50% better patient outcomes for cancer treatment. The programme uses genomic testing, AI analysis, and targeted therapies to create personalised treatment plans. With £150 million in government funding, the initiative aims to make precision medicine available across all NHS trusts by 2026.", "doc_type": DocType.news, "sector": "Health"},
    {"title": "UK PropTech Sector Attracts £1 Billion Investment", "content": "The UK property technology sector has attracted over £1 billion in investment as digital transformation reshapes real estate. Key innovations include AI-powered property valuations, blockchain land registries, IoT-enabled building management, and virtual viewings. The sector is creating 5,000 new jobs annually and helping the UK construction industry address its productivity challenge.", "doc_type": DocType.news, "sector": "IoT"},
    {"title": "RegTech Revolution: UK Leads Global Regulatory Technology", "content": "The UK has established itself as the global leader in regulatory technology, with over 400 RegTech firms generating £5 billion in revenue. The FCA's proactive approach to innovation, including the regulatory sandbox and TechSprints, has created a supportive ecosystem. Key areas include automated compliance monitoring, KYC/AML solutions, and regulatory reporting automation. International demand for UK RegTech is growing 40% annually.", "doc_type": DocType.news, "sector": "Business"},
    {"title": "UK EdTech Export Revenue Exceeds £700 Million", "content": "UK educational technology exports have exceeded £700 million, with AI tutoring platforms, virtual classrooms, and learning analytics tools in high demand globally. The pandemic accelerated digital learning adoption, and UK EdTech companies are now expanding into Asia, Africa, and the Middle East. The government's EdTech Strategy supports innovation through grants and international trade missions.", "doc_type": DocType.news, "sector": "IT"},
    {"title": "Carbon Trading Platform for UK Agriculture Launches", "content": "A new digital platform for trading agricultural carbon credits has launched, connecting UK farmers with corporate carbon offset buyers. Using satellite monitoring and soil testing, the platform verifies carbon sequestration from regenerative farming practices. Over 500 farms have registered, with average additional income of £30 per hectare annually from carbon credit sales.", "doc_type": DocType.news, "sector": "Agriculture"},
    {"title": "UK Retail Innovation: Same-Day Delivery Becomes Standard", "content": "Same-day delivery has become the standard expectation for UK online shoppers, with 60% of major retailers now offering the service. AI-powered logistics optimisation and micro-fulfilment centres in urban areas have made this economically viable. UK logistics tech startups have raised £800 million to build the infrastructure supporting this transformation.", "doc_type": DocType.news, "sector": "Ecommerce"},
    {"title": "UK Quantum Computing Roadmap Targets Commercial Viability", "content": "The UK government has published a 10-year quantum computing roadmap with £900 million in public funding. The roadmap targets commercial viability by 2030, with intermediate milestones for quantum advantage in specific applications. UK quantum companies including Oxford Quantum Circuits and Riverlane are developing hardware and software for finance, pharmaceutical, and logistics applications.", "doc_type": DocType.news, "sector": "IT"},
    {"title": "Connected Farms: UK Agricultural IoT Adoption Reaches 35%", "content": "IoT adoption on UK farms has reached 35%, driven by declining sensor costs and improved rural connectivity. Common applications include soil moisture monitoring, automated irrigation, GPS-guided machinery, and livestock tracking. Farmers using connected technologies report average productivity gains of 15% and input cost reductions of 20%.", "doc_type": DocType.news, "sector": "Agriculture"},
    # Policy documents
    {"title": "UK Innovation Strategy 2025-2030", "content": "The UK Innovation Strategy sets out the government's vision for making the UK a global hub for innovation. Key priorities include: 1) Unleashing business innovation through R&D tax credits and the Patent Box scheme, 2) Supporting people and skills through the Global Talent Visa and STEM education initiatives, 3) Building innovation institutions including catapult centres and regulatory sandboxes, 4) Driving innovation in every region through Levelling Up funds and regional innovation clusters, 5) International collaboration through Horizon Europe association and bilateral science agreements. The strategy commits £22 billion annually to R&D by 2026 and aims to make the UK the most innovative economy in the world.", "doc_type": DocType.policy, "sector": None},
    {"title": "Innovator Founder Visa Requirements and Criteria", "content": "The UK Innovator Founder Visa (replacing the Innovator Visa from April 2023) is designed for experienced business people seeking to establish an innovative business in the UK. Key requirements: 1) Endorsement from an approved endorsing body, 2) The business idea must be innovative - genuinely new or significantly different from anything else on the market, 3) The idea must be viable - with evidence of a realistic business model and market, 4) The idea must be scalable - potential for significant growth, creating jobs and economic impact, 5) The applicant must have at least £50,000 in investment funds, 6) English language proficiency at B2 level. The endorsing body assesses the innovation, viability, and scalability criteria. Successful applicants receive a 3-year visa with a path to settlement.", "doc_type": DocType.policy, "sector": None},
    {"title": "Innovate UK Smart Grants Programme Guide", "content": "Innovate UK Smart Grants provide up to £500,000 for innovative projects with strong commercial potential. The programme is open to UK-registered businesses of any size, working alone or in collaboration. Assessment criteria: 1) Innovation (how novel and ambitious the idea is), 2) Market opportunity (evidence of customer demand and market size), 3) Team (skills, experience, and track record), 4) Project plan (deliverability, milestones, and risk management), 5) Value for money (justification of costs and expected return on investment). Applications are assessed by independent experts and compete against other applications in the same round. Funding covers 50-70% of eligible project costs depending on company size.", "doc_type": DocType.policy, "sector": None},
    {"title": "UKRI Technology Readiness Levels Framework", "content": "UKRI uses Technology Readiness Levels (TRLs) to assess the maturity of innovations. TRL 1: Basic research, TRL 2: Technology concept formulated, TRL 3: Proof of concept, TRL 4: Technology validated in lab, TRL 5: Technology validated in relevant environment, TRL 6: Technology demonstrated in relevant environment, TRL 7: System prototype in operational environment, TRL 8: Actual system completed and qualified, TRL 9: Actual system proven in operational environment. Most Innovate UK grants target TRL 3-7, bridging the 'valley of death' between research and commercialisation. Understanding your TRL helps you target the right funding programme.", "doc_type": DocType.policy, "sector": None},
    {"title": "UK Intellectual Property Strategy for Innovators", "content": "The UK's intellectual property framework is a key asset for innovators. Key elements: 1) Patents - 20-year protection for novel inventions, UK IPO offers fast-track 'Green Channel' for environmentally beneficial inventions, 2) Trade marks - protection for brand identity, online registration available, 3) Design rights - automatic protection for original designs, registered designs offer stronger protection, 4) Trade secrets - protection through NDAs and employment contracts, 5) The Patent Box regime reduces corporation tax on profits from patented inventions to 10%. UK IP rights are enforceable globally through international treaties and are a key consideration for visa endorsement bodies assessing innovation.", "doc_type": DocType.policy, "sector": None},
    {"title": "Net Zero Innovation Portfolio", "content": "The UK government's £1 billion Net Zero Innovation Portfolio funds the development of low-carbon technologies across 10 priority areas: 1) Advanced nuclear, 2) Hydrogen production and storage, 3) Carbon capture, utilisation and storage, 4) Green finance, 5) Sustainable aviation fuel, 6) Industrial decarbonisation, 7) Smart energy systems, 8) Natural environment, 9) Buildings, 10) Future transport. The portfolio supports projects from proof of concept through to large-scale demonstration, with additional funding from matched industry investment.", "doc_type": DocType.policy, "sector": None},
    {"title": "UK Digital Strategy: Digital Skills and Infrastructure", "content": "The UK Digital Strategy focuses on three pillars: 1) Digital infrastructure - £5 billion for gigabit broadband and nationwide 5G coverage by 2030, 2) Digital skills - the National Skills Fund provides £2.5 billion for digital training, coding bootcamps, and AI literacy programmes, 3) Digital government - all public services to be available digitally, with £1.2 billion invested in NHS digital transformation. The strategy also addresses digital inclusion, ensuring 95% of the population has basic digital skills by 2030.", "doc_type": DocType.policy, "sector": "IT"},
    {"title": "Post-Brexit Trade and Innovation Policy", "content": "The UK's post-Brexit trade policy creates new opportunities for innovative businesses. Key elements: 1) Independent trade agreements with fast-growing markets (Australia, Japan, CPTPP), 2) The UK's own regulatory frameworks allow faster innovation in areas like AI, genomics, and autonomous vehicles, 3) The Global Innovation Fund supports UK-international research collaboration, 4) The Developing Countries Trading Scheme provides preferential access for UK innovations in emerging markets. While EU market access requires regulatory alignment, the UK's regulatory autonomy enables innovation in areas where EU rules are more restrictive.", "doc_type": DocType.policy, "sector": "Business"},
    {"title": "NHS Long Term Plan: Technology and Innovation", "content": "The NHS Long Term Plan commits to: 1) Every patient having access to digital GP services by 2024, 2) AI screening for cancer, cardiovascular disease, and eye conditions rolled out across all NHS trusts, 3) A new NHS Innovation Service to help innovators navigate the health system, 4) £250 million annual funding for NHS clinical research with technology companies, 5) Digital-first approach to outpatient appointments, with 30% conducted remotely. The plan specifically encourages partnerships with technology startups and has created 15 NHS Innovation Accelerators to fast-track promising technologies.", "doc_type": DocType.policy, "sector": "Health"},
    {"title": "DEFRA Environmental Land Management Scheme", "content": "The Environmental Land Management (ELM) scheme replaces EU Common Agricultural Policy payments in England. The scheme pays farmers for environmental outcomes including: 1) Sustainable Farming Incentive - standards for soil health, integrated pest management, and nutrient management, 2) Local Nature Recovery - habitat creation and restoration, 3) Landscape Recovery - large-scale ecosystem restoration. Technology plays a key role: satellite monitoring verifies compliance, IoT sensors measure environmental outcomes, and digital platforms facilitate payment administration. The scheme creates opportunities for AgriTech companies providing monitoring and verification tools.", "doc_type": DocType.policy, "sector": "Agriculture"},
    {"title": "UK AI Regulation: Pro-Innovation Approach", "content": "The UK government has adopted a pro-innovation approach to AI regulation, avoiding a single AI regulator in favour of sector-specific oversight. Key principles: 1) Safety and security, 2) Transparency and explainability, 3) Fairness and non-discrimination, 4) Accountability and governance, 5) Contestability and redress. The approach gives UK AI companies more flexibility than the EU AI Act, potentially creating a competitive advantage. The AI Safety Institute, based in London, leads global AI safety research and testing.", "doc_type": DocType.policy, "sector": "IT"},
    {"title": "UK Fintech Strategy and Regulatory Sandbox", "content": "The UK's fintech strategy positions London as the global fintech capital through: 1) The FCA Regulatory Sandbox allowing innovative firms to test products with real customers under relaxed regulations, 2) Open Banking and the move towards Open Finance giving consumers control over their financial data, 3) The Fintech Bridges programme establishing regulatory cooperation with 30+ countries, 4) The Bank of England's approach to stablecoins and Central Bank Digital Currency research, 5) R&D tax credits specifically enhanced for financial services innovation.", "doc_type": DocType.policy, "sector": "Business"},
    # Research papers
    {"title": "Transformer Models for Medical Image Analysis: A UK Multi-Centre Study", "content": "This peer-reviewed study from Imperial College London, University of Edinburgh, and King's College London evaluated vision transformer models for analysing 500,000 medical images across 12 NHS trusts. The models achieved radiologist-level accuracy (AUC 0.98) for detecting lung nodules, brain haemorrhages, and breast lesions. The study demonstrates that AI diagnostic tools can significantly reduce reporting backlogs in the NHS, where 28% of radiology positions are unfilled. The research was funded by UKRI and the Wellcome Trust.", "doc_type": DocType.research, "sector": "Health"},
    {"title": "Federated Learning Privacy Guarantees: Theoretical Framework and UK Applications", "content": "This Cambridge University paper establishes mathematical privacy guarantees for federated learning systems deployed in UK healthcare and finance contexts. The framework proves that with differential privacy noise calibrated to ε=1.0, individual data records cannot be reconstructed with probability exceeding 10^-6. Practical applications include multi-bank fraud detection and cross-trust NHS AI training, both of which face strict data protection requirements under UK GDPR.", "doc_type": DocType.research, "sector": "IT"},
    {"title": "Economic Impact of AgriTech Adoption on UK Small Farms", "content": "This DEFRA-commissioned study by the University of Reading quantifies the economic impact of technology adoption on UK farms under 200 hectares. Results from 1,500 farms show that precision agriculture technologies increase net profit by £45/hectare on average, IoT soil sensors reduce fertiliser costs by 22%, and GPS-guided machinery reduces overlap waste by 15%. However, adoption barriers include high upfront costs, lack of rural broadband, and limited technical skills.", "doc_type": DocType.research, "sector": "Agriculture"},
    {"title": "Consumer Trust in AI-Powered E-commerce Recommendations", "content": "This London Business School study surveyed 5,000 UK online shoppers on their attitudes toward AI product recommendations. Key findings: 65% of consumers are more likely to purchase when recommendations explain why an item was suggested, transparency about AI use increases trust by 40%, and personalisation that respects privacy boundaries increases repeat purchases by 25%. The study provides actionable guidelines for UK e-commerce businesses implementing AI recommendation systems.", "doc_type": DocType.research, "sector": "Ecommerce"},
    {"title": "Energy Efficiency of Edge Computing vs Cloud for IoT Analytics", "content": "This University of Bristol study compares energy consumption of edge vs cloud computing architectures for IoT data analytics. Results show that edge computing reduces energy use by 40% for real-time applications and cuts data transfer costs by 90%. However, cloud computing remains more efficient for batch processing of historical data. The paper proposes a hybrid architecture optimised for UK smart city deployments.", "doc_type": DocType.research, "sector": "IoT"},
    {"title": "Impact of Open Banking on UK SME Lending Decisions", "content": "This Bank of England working paper analyses how open banking data improves lending decisions for UK SMEs. Using data from 10,000 loan applications, the study shows that incorporating transaction data reduces default rates by 30% and increases approval rates for creditworthy businesses by 25%. Open banking particularly benefits minority-owned businesses and those in underserved regions.", "doc_type": DocType.research, "sector": "Business"},
    {"title": "Natural Language Processing for Clinical Note Extraction in NHS", "content": "This joint UCL-NHS Digital study developed NLP models for extracting structured data from unstructured NHS clinical notes. The models, trained on 2 million anonymised notes, achieved 94% accuracy for identifying diagnoses, medications, and procedures. The system addresses a critical bottleneck in NHS data analytics and supports population health management initiatives.", "doc_type": DocType.research, "sector": "Health"},
    {"title": "Autonomous Vehicle Testing Safety Framework: UK Regulatory Analysis", "content": "This University of Warwick paper proposes a safety testing framework for autonomous vehicles aligned with UK regulations. The framework defines 150 critical test scenarios specific to UK road conditions, weather patterns, and driving behaviours. It has been adopted by the Centre for Connected and Autonomous Vehicles as a recommended standard for UK AV testing.", "doc_type": DocType.research, "sector": "IT"},
    {"title": "Machine Learning for Soil Carbon Prediction: UK Agricultural Lands", "content": "This Rothamsted Research paper presents ML models predicting soil organic carbon levels across UK agricultural lands using satellite imagery, weather data, and soil surveys. The random forest model achieves R²=0.87 accuracy, enabling cost-effective carbon stock monitoring at national scale. The research supports the UK's agricultural carbon credit verification infrastructure.", "doc_type": DocType.research, "sector": "Agriculture"},
    {"title": "Blockchain Adoption Barriers in UK Retail Supply Chains", "content": "This Cranfield University study identifies key barriers to blockchain adoption in UK retail supply chains through interviews with 50 UK retailers and suppliers. Major barriers include interoperability with existing systems (cited by 80%), lack of industry standards (65%), cost uncertainty (60%), and skills gaps (55%). The paper proposes a phased adoption framework with quick wins in provenance tracking and compliance.", "doc_type": DocType.research, "sector": "Ecommerce"},
    {"title": "5G Network Slicing for Industrial IoT: Performance Evaluation", "content": "This University of Surrey 5G Innovation Centre paper evaluates network slicing performance for industrial IoT applications. Tests on a live 5G network demonstrate that dedicated network slices achieve 99.999% reliability and sub-1ms latency for critical manufacturing applications. The research validates 5G as a viable alternative to wired industrial networks.", "doc_type": DocType.research, "sector": "IoT"},
    {"title": "AI Bias in UK Financial Services: Detection and Mitigation", "content": "This Alan Turing Institute paper analyses AI bias in UK financial services decision-making. The study found that 38% of AI models used for credit scoring exhibited demographic bias exceeding FCA guidelines. The paper presents debiasing techniques that maintain prediction accuracy while reducing protected-characteristic disparities by 80%.", "doc_type": DocType.research, "sector": "Business"},
    {"title": "Digital Biomarkers for Mental Health: Smartphone Sensing Study", "content": "This King's College London study explores using smartphone sensor data as digital biomarkers for mental health conditions. Analysing data from 3,000 UK participants, the researchers identified patterns in typing speed, screen time, and movement that predict depressive episodes 7 days in advance with 78% accuracy. The research supports the development of AI-powered mental health apps.", "doc_type": DocType.research, "sector": "Health"},
    {"title": "Reinforcement Learning for Energy Grid Optimisation", "content": "This Imperial College paper develops reinforcement learning algorithms for optimising UK energy grid operations with high renewable penetration. The RL agent learned to balance supply and demand with 30% higher efficiency than traditional methods, reducing curtailment of renewable energy by 45%. The approach is being piloted with National Grid ESO.", "doc_type": DocType.research, "sector": "IoT"},
    {"title": "Synthetic Data Generation for UK Healthcare AI Development", "content": "This Oxford University paper presents methods for generating realistic synthetic patient data that preserves statistical properties while protecting individual privacy. The synthetic data, validated against real NHS datasets, enables AI researchers to develop and test healthcare models without accessing real patient records. The approach has been endorsed by NHS Digital for use in AI development programmes.", "doc_type": DocType.research, "sector": "IT"},
    {"title": "UK Vertical Farming Economics: Cost-Benefit Analysis", "content": "This Harper Adams University study provides a comprehensive cost-benefit analysis of vertical farming in the UK context. With current technology, vertical farms achieve profitability at scale for leafy greens and herbs, with payback periods of 5-7 years. The study identifies automation, LED efficiency improvements, and renewable energy as key factors that will make vertical farming viable for a broader range of UK crops by 2028.", "doc_type": DocType.research, "sector": "Agriculture"},
    {"title": "Customer Lifetime Value Prediction in UK Subscription Commerce", "content": "This Warwick Business School paper develops ML models for predicting customer lifetime value in UK subscription e-commerce businesses. Using data from 100,000 subscribers across 5 UK companies, the gradient boosting model predicts 12-month CLV with 85% accuracy. Key features include early engagement patterns, payment method, and geographic factors specific to UK consumers.", "doc_type": DocType.research, "sector": "Ecommerce"},
    {"title": "Secure Multi-Party Computation for Cross-Border Data Sharing", "content": "This University of Edinburgh paper demonstrates practical secure multi-party computation protocols for sharing sensitive business data across UK and EU organisations post-Brexit. The system enables joint analytics on financial and healthcare data while maintaining compliance with both UK GDPR and EU GDPR. Processing overhead is reduced to 3x compared to plaintext computation.", "doc_type": DocType.research, "sector": "IT"},
    {"title": "Robotic Process Automation Impact on UK Public Sector Efficiency", "content": "This LSE study analyses the impact of RPA deployment across 20 UK local councils. Results show average cost savings of 35%, processing time reductions of 80%, and error rate decreases of 95% for routine administrative tasks. However, the study emphasises that successful RPA requires investment in change management and digital skills training for existing staff.", "doc_type": DocType.research, "sector": "Business"},
    {"title": "Wearable Sensor Accuracy for Remote Patient Monitoring", "content": "This University of Manchester clinical study evaluates the accuracy of consumer wearable sensors for remote patient monitoring in the NHS. Testing 8 popular wearable devices against clinical-grade equipment, the study found that heart rate accuracy exceeded 95% for all devices, blood oxygen monitoring was reliable above 90% SpO2, but sleep tracking varied significantly. The paper provides recommendations for which wearable data can be safely used in clinical decision-making.", "doc_type": DocType.research, "sector": "Health"},
]


def seed_documents(db):
    if db.query(Document).count() > 0:
        print("Documents already seeded, skipping.")
        return

    sectors = {s.name: s.id for s in db.query(Sector).all()}

    for d in DOCUMENT_CONTENT:
        sid = sectors.get(d.get("sector")) if d.get("sector") else None
        chash = _hash(d["content"])

        doc = Document(
            title=d["title"],
            content=d["content"],
            content_hash=chash,
            doc_type=d["doc_type"],
            sector_id=sid,
            published_at=NOW - timedelta(days=random.randint(1, 365)),
            metadata_={"source": "seed", "sector": d.get("sector", "general")},
        )
        db.add(doc)

    db.commit()
    count = len(DOCUMENT_CONTENT)
    print(f"Seeded {count} documents.")

    # Generate embeddings if RAG engine is available
    if HAS_RAG and _rag:
        print("Generating embeddings for seeded documents...")
        docs = db.query(Document).filter(Document.embedding_stored == False).all()  # noqa: E712
        for i, doc in enumerate(docs):
            try:
                _rag.ingest_document(doc, db)
                if (i + 1) % 10 == 0:
                    print(f"  Embedded {i + 1}/{len(docs)} documents...")
            except Exception as exc:
                print(f"  Warning: Failed to embed '{doc.title[:50]}': {exc}")
        print("Embedding complete.")


def seed_competitions(db):
    if db.query(Competition).count() > 0:
        print("Competitions already seeded, skipping.")
        return

    sectors = {s.name: s.id for s in db.query(Sector).all()}
    today = date.today()

    competitions = [
        {"title": "Smart Grants: Innovation in Health and Life Sciences", "description": "Innovate UK invites UK registered businesses to apply for a share of up to £25 million for innovative projects in health and life sciences. Projects must demonstrate clear innovation, strong commercial potential, and contribute to improving patient outcomes or healthcare efficiency. Collaboration with NHS trusts is encouraged but not required. Eligible costs include staff time, subcontracting, materials, equipment, and travel.", "sector": "Health", "funding": 2_500_000, "status": CompetitionStatus.open, "deadline_offset": 45},
        {"title": "AI for Net Zero Challenge Fund", "description": "A £10 million challenge fund supporting AI applications that accelerate the UK's transition to net zero emissions. Projects should use artificial intelligence to reduce energy consumption, optimise renewable energy systems, improve carbon measurement, or enable circular economy solutions. Open to UK-registered businesses and academic institutions. Priority given to projects with clear deployment pathways within 24 months.", "sector": "IT", "funding": 5_000_000, "status": CompetitionStatus.open, "deadline_offset": 60},
        {"title": "Future of Retail Innovation Competition", "description": "Innovate UK seeks innovative solutions that will shape the future of UK retail. Areas of interest include AI-powered personalisation, sustainable supply chains, immersive shopping experiences, and accessibility innovations. Grants of £50,000 to £500,000 available for feasibility studies and prototype development. Partnerships between retailers and technology companies encouraged.", "sector": "Ecommerce", "funding": 500_000, "status": CompetitionStatus.open, "deadline_offset": 30},
        {"title": "Farming Innovation Programme: Sustainable Production", "description": "DEFRA and Innovate UK co-fund this programme supporting innovations in sustainable farming. Projects should address soil health, water management, biodiversity, or carbon reduction while maintaining or improving farm productivity. Grants of £100,000 to £1 million available. Must involve at least one UK farming business.", "sector": "Agriculture", "funding": 1_000_000, "status": CompetitionStatus.open, "deadline_offset": 75},
        {"title": "Connected Places Catapult: Smart Infrastructure", "description": "Funding for IoT and digital infrastructure projects that improve UK urban environments. Focus areas include intelligent transport, environmental monitoring, public safety, and citizen services. Collaborative projects between technology companies and local authorities receive priority. Grants of £200,000 to £2 million.", "sector": "IoT", "funding": 2_000_000, "status": CompetitionStatus.open, "deadline_offset": 90},
        {"title": "FinTech Growth Fund Round 3", "description": "The third round of the FinTech Growth Fund provides grants of £250,000 to £750,000 for UK fintech companies scaling innovative financial services products. Applicants must demonstrate product-market fit and a clear path to international expansion. Assessment focuses on innovation, regulatory compliance, and potential for UK financial services sector benefit.", "sector": "Business", "funding": 750_000, "status": CompetitionStatus.upcoming, "deadline_offset": 120},
        {"title": "NHS Clinical AI Implementation Programme", "description": "NHS England and Innovate UK joint programme funding the implementation of proven AI tools in NHS settings. Projects must use AI technologies with evidence of clinical effectiveness and focus on deployment, integration, and evaluation in live NHS environments. Grants of £500,000 to £3 million.", "sector": "Health", "funding": 3_000_000, "status": CompetitionStatus.upcoming, "deadline_offset": 150},
        {"title": "Quantum Technologies Challenge", "description": "UKRI challenge fund for quantum computing, sensing, and communications applications. Projects should move quantum technologies from laboratory to commercial applications in areas like drug discovery, logistics optimisation, or secure communications. Large-scale collaborative projects of £1 million to £5 million.", "sector": "IT", "funding": 5_000_000, "status": CompetitionStatus.upcoming, "deadline_offset": 180},
        {"title": "Sustainable Supply Chains Innovation Fund (Closed)", "description": "This competition funded innovations in supply chain sustainability, including carbon tracking, ethical sourcing verification, and circular logistics. 15 projects were funded totalling £8 million. Results and case studies are available on the Innovate UK website.", "sector": "Ecommerce", "funding": 800_000, "status": CompetitionStatus.closed, "deadline_offset": -30},
        {"title": "Smart Farming Equipment R&D (Closed)", "description": "Closed competition that funded research and development of next-generation smart farming equipment. 10 projects were awarded grants totalling £5 million, covering autonomous machinery, sensor systems, and data platforms for UK agriculture.", "sector": "Agriculture", "funding": 500_000, "status": CompetitionStatus.closed, "deadline_offset": -60},
    ]

    for c in competitions:
        dl = today + timedelta(days=c["deadline_offset"]) if c["deadline_offset"] > 0 else today + timedelta(days=c["deadline_offset"])
        comp = Competition(
            title=c["title"],
            description=c["description"],
            url="https://www.ukri.org/what-we-offer/browse-our-areas-of-investment-and-support/",
            deadline=dl,
            sector_id=sectors.get(c["sector"]),
            funding_amount_gbp=c["funding"],
            applicant_requirements="UK registered business. Must demonstrate innovation, commercial viability, and UK economic benefit.",
            status=c["status"],
        )
        db.add(comp)

    db.commit()
    print(f"Seeded {len(competitions)} competitions.")


def seed_test_user(db):
    if db.query(User).filter(User.email == "test@innovisa.ai").first():
        print("Test user already exists, skipping.")
        return

    user = User(
        email="test@innovisa.ai",
        hashed_password=hash_password("InnoVisaTest2024!"),
        full_name="Test User",
        onboarding_data={
            "skills": ["Python", "Machine Learning", "Product Management", "Data Analysis"],
            "interests": ["Healthcare AI", "FinTech", "Sustainability", "IoT"],
            "background": "5 years in software engineering with a focus on AI/ML applications",
            "timeline": "6 months",
        },
        subscription_tier=SubscriptionTier.pro,
    )
    db.add(user)
    db.flush()

    # Save first 5 ideas for this user
    ideas = db.query(Idea).limit(5).all()
    for idea in ideas:
        saved = SavedIdea(
            user_id=user.id,
            idea_id=idea.id,
            user_notes=f"Interesting project idea in {idea.title[:30]} area. Worth exploring further.",
        )
        db.add(saved)

    db.commit()
    print("Seeded test user (test@innovisa.ai / InnoVisaTest2024!) with 5 saved ideas.")


def main():
    print("=" * 60)
    print("InnoVisa AI - Database Seed Script")
    print("=" * 60)

    # Create tables if they don't exist (for first run before alembic)
    Base.metadata.create_all(bind=engine)
    print("Database tables ensured.")

    db = SessionLocal()
    try:
        seed_sectors(db)
        seed_ideas(db)
        seed_documents(db)
        seed_competitions(db)
        seed_test_user(db)
        print("\n" + "=" * 60)
        print("Seeding complete!")
        print(f"  Sectors:      {db.query(Sector).count()}")
        print(f"  Ideas:        {db.query(Idea).count()}")
        print(f"  Documents:    {db.query(Document).count()}")
        print(f"  Competitions: {db.query(Competition).count()}")
        print(f"  Users:        {db.query(User).count()}")
        print("=" * 60)
    finally:
        db.close()


if __name__ == "__main__":
    main()
